# Uncomment the next line to define a global platform for your project
platform :ios, '12.2'

target 'Toptenplus' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'

  target 'ToptenplusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ToptenplusUITests' do
    inherit! :search_paths
    # Pods for UI testing
  end
end
